name: Github CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        boost_version: 1.73.0
    - run: pip install meson ninja cram
    - run: mkdir /home/runner/work/hmcnc/hmcnc/installdir
    - run: meson setup --prefix /home/runner/work/hmcnc/hmcnc/installdir builddir/
      env:
        CC: gcc
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - run: meson install -C builddir/
    - run: meson test -C builddir/ -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        boost_version: 1.73.0
    - run: brew install gcc
    - run: pip install meson ninja cram
    - run: meson setup builddir/
      env:
        CC: gcc
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - run: meson install -C builddir/
    - run: meson test -C builddir/ -v
